### ISSUE TITLE
Partial Undressing not always providing the proper items

### ISSUE THREAD

**Issue by Dataweaver42** [Vin-meido/COM3D2.UndressUtil#1]
This has become crystal clear when used in conjunction with DressCode, but it's a problem even without it: any time the maid's costume is temporarily changed (such as what DressCode does, but also in scenes where you visit a maid at work), the Porori controls are set based off of the standard costume instead of its temporary replacement. This causes weird and (for the duration of the scene) irreversible changes to the maid's outfit.

**Comment by Vin-meido** [comment]
Can you see if this fixes it.
[COM3D2.UndressUtil.zip](https://github.com/Vin-meido/COM3D2.UndressUtil/files/13852279/COM3D2.UndressUtil.zip)

**Comment by Dataweaver42** [comment]
That did it. Everything's working properly now.
